#!/bin/bash

sv check redis
sv check hhvm

if [[ ! -d /var/log/nginx ]]; then
	mkdir /var/log/nginx \
	&& chown nginx /var/log/nginx
fi

if [[ ! -e /etc/ssl/web/web.key ]]; then
	echo "About to generate self-signed certificates for Nginx"

	# secret key
	umask 0177
	openssl ecparam -out /etc/ssl/web/web.key -name prime256v1 -genkey
	umask 0022

	# CSR, in case you want to submit it to any known CA
	# see: openssl req -in web.csr -noout -text
	openssl req -new -nodes -sha384 \
		-subj '/C=PH/ST=Zambales/L=Olongapo/O=LaraDev/CN=royalflushnetwork.com/emailAddress=hostmaster@royaflushnetwork.com' \
		-key /etc/ssl/web/web.key -out /etc/ssl/web/web.csr

	# We'll generate a self-signed cert for now, though.
	# see: openssl x509 -in web.crt-bundle -noout -text
	openssl req -new -x509 -sha384 \
		-set_serial 100 -days 31 \
		-subj '/C=PH/ST=Zambales/L=Olongapo/O=LaraDev/CN=royalflushnetwork.com/emailAddress=hostmaster@royaflushnetwork.com' \
		-key /etc/ssl/web/web.key -out /etc/ssl/web/web.crt-bundle
fi

echo "Starting Nginx"
exec 2>&1 \
	/usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
