#!/bin/bash

if [[ ! -d /var/log/redis ]]; then
	mkdir /var/log/redis \
	&& chown redis:redis /var/log/redis
fi

sed -i -e 's:^save:# save:g' \
	-e 's:^bind:# bind:g' \
	-e 's:^logfile:# logfile:' \
	-e 's:daemonize yes:daemonize no:' \
	-e 's:# maxmemory \(.*\)$:maxmemory 248435456:' \
	-e 's:# maxmemory-policy \(.*\)$:maxmemory-policy volatile-lru:' \
	/etc/redis/redis.conf

echo "Starting Redis"
exec 2>&1
exec /usr/bin/chpst -u redis:redis \
	/usr/bin/redis-server /etc/redis/redis.conf
