#!/bin/bash

source /etc/envvars
exec 2>&1

if [[ ! -d /var/log/hhvm ]]; then
	mkdir -p /var/log/hhvm
fi
chown owner /var/log/hhvm

if [[ ! -d /var/cache/hhvm ]]; then
	mkdir -p /var/cache/hhvm
fi
chown -R owner /var/cache/hhvm

if [[ ! -d /home/owner ]]; then
	mkdir -p /home/owner
fi
chown owner /home/owner

if [[ ! -s /var/cache/hhvm/hhvm.hhbc ]]; then
  echo "Pre-generating cache for HHVM"
  /usr/bin/chpst -u owner:www-data \
    /usr/bin/hhvm --hphp --target hhbc \
      -v AllVolatile=true \
      --output-dir /var/cache/hhvm \
      --input-dir /var/www/html
fi

echo "Starting HHVM"
HHVM_MAXPROCS=$((2 + $(nproc) ))
cd /var/www/html
exec /usr/bin/chpst -u owner:www-data -p ${HHVM_MAXPROCS} \
  /usr/bin/hhvm \
    -v Eval.Jit=1 \
    -v Server.SourceRoot=/var/www/html \
    --mode server -v Server.Type=fastcgi -v Server.Port=9000
